name: ArrowHearts
description: Gives the damager who shots a player how much health they have left!
version: "1.0_beta"
main: arrow\Main
author: OpenBuild Dev Team (Pogogo007 SavionLegendZzz)
api: 1.13.0